### PR TITLE
feat: entrypoints and transactions card static ui

### LINKED ISSUE #11: Data tile FE: Entrypoints and Transactions
Feel free to join our telegram to get latest updates: https://t.me/+DYI4FMia43I1NDI8

Related backend tasks:
* https://github.com/walnuthq/starkflare/issues/9
* https://github.com/walnuthq/starkflare/issues/10

Implement the "Entrypoints and Transactions" tile (file named `entrypoints.tsx`) based on the following description and mock.
* It should contain an input field, where the user can specify a contract ID. The default contract ID will be pre-set to [Carmine](https://starkscan.co/contract/0x047472e6755afc57ada9550b6a3ac93129cc4b5f98f51c73e0644d129fd208d9#overview)
* It should contain a list of Entrypoints of a given contract, sorted by the amount of steps used. Use vertical scroll if the list is too large
* Above entrypoints, there will be a visualisation of each entrypoint usage. See the "Visual inspiration for the Entrypoints section" screenshot below
* On the right side, there will be a "Transactions" section with a list of transactions for a selected Entrypoint. It will be possible to select a different entrypoint using a little select box in the description below "Transactions" header (see mock below). Each transaction will contain a hash and a number of steps consumed. Bonus points for also showing the timestamp of the transaction.

Visual inspiration for the Entrypoints section:  CleanShot 2024-05-20 at 15 38 44@2x

Mock of the whole tile:
image

Note: if the backend tasks are not ready, it's OK to mock the data in a hardcoded JSON.

**Specification missing: ‼️**
Update based on our ability to get the data from the API; cc @barabanovro

### PR DESCRIPTION
**Pull request by bhavyagosai**
- resolves #11
- added packages and components:
    - dayjs
    - shadcn components:
        - tooltip
        - label
        - input
        - select
        - table
        - skeleton
- added extended components for better code + features + reusability
    - common-tooltip
      - added `hideOnClick` boolean prop
    - common-select
      - set a max height for the select dropdown
    - input-extended
      - added adornment support
- added static data 
- added custom scrollbar
- added loaders wherever needed
- added tooltips to data wherever deemed necessary
- added copy support to transaction hashes
- cycling through 10 static colors in stacked bar chart

Note: 
- static height added in order to let data cap at specific length and scroll
- scrollbar in scrollable components is always visible for better ux
- card heading changed according to ui (non uniform now)

### CODE REVIEW

**Review by melnikga — CHANGES_REQUESTED** [review]
Hello, please make the following changes:
1. Fix lint errors
image

4. I noticed that you import the Input component from shadcn, but don't use it. Instead, you create your own using the standard html tag "input".  It is necessary to use the Input component from shadcn

**Review by melnikga — APPROVED** [review]
LGTM!

**Comment by melnikga** [comment]
@bhavyagosai resolve branch conflicts

**Comment by bhavyagosai** [comment]
resolved!

**Review by melnikga — CHANGES_REQUESTED** [review]
@bhavyagosai can you please fix the merge conflicts again?

**Review by romanbarbo — APPROVED** [review]

**Pull request merged**
